DELETE FROM VERS;

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(0, 'Initial version', 'Y', '0000-00-00');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(1, 'Release~3', 'Y', '1994-01-01');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(2, 'Release~4', 'Y', '1995-11-12');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(3, 'Release~4 Version~0.37', 'N', '1995-12-22');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(4, 'Release~4 Version~0.38', 'N', '1995-12-27');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(5, 'Release~4 Version~0.39', 'N', '1996-01-06');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(6, 'Release~4 Version~0.40', 'N', '1996-01-20');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(7, 'Release~4 Version~0.41', 'N', '1996-01-24');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(8, 'Release~4 Version~0.42', 'N', '1996-01-25');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(9, 'Release~4 Version~0.43', 'N', '1996-02-11');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(10, 'Release~4 Version~0.44', 'N', '1996-02-23');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(11, 'Release~4 Version~0.45', 'N', '1996-03-02');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(12, 'Release~4 Version~0.46', 'N', '1996-03-11');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(13, 'Release~4 Version~0.47', 'N', '1996-03-27');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(14, 'Release~4 Version~0.48', 'N', '1996-04-08');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(15, 'Release~5', 'Y', '1996-04-18');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(16, 'Release~5 Version~0.49', 'N', '1996-04-28');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(17, 'Release~5 Patchlevel~2', 'N', '1996-05-19');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(18, 'Release~5 Patchlevel~3', 'N', '1996-05-22');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(19, 'Release~5 Patchlevel~4', 'N', '1996-05-31');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(20, 'Release~5 Patchlevel~5', 'N', '1996-06-31');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(21, 'Release~5 Patchlevel~6', 'N', '1996-07-17');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(22, 'Release~5 Patchlevel~7', 'N', '1996-07-29');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(23, 'Release~5 Patchlevel~8', 'N', '1996-08-08');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(24, 'Release~5 Patchlevel~9', 'N', '1996-08-17');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(25, 'Release~5 Patchlevel~10', 'N', '1996-08-27');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(26, 'Release~5 Patchlevel~11', 'N', '1996-09-17');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(27, 'Release~5 Patchlevel~12', 'N', '1996-10-04');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(28, 'Release~5 Patchlevel~13', 'N', '1996-10-13');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(29, 'Release~5 Patchlevel~14', 'N', '1996-11-16');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(30, 'Release~5 Patchlevel~15', 'N', '1996-11-29');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(31, 'Release~5 Patchlevel~16', 'N', '1996-12-14');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(32, 'Release~6', 'Y', '1997-01-02');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(33, 'Release~6 Patchlevel~0', 'N', '1997-01-02');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(34, 'Release~6 Patchlevel~1', 'N', '1997-02-10');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(35, 'Release~6 Patchlevel~2', 'N', '1997-03-26');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(36, 'Release~6 Patchlevel~3', 'N', '1997-04-04');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(37, 'Release~6 Patchlevel~4', 'N', '1997-06-25');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(38, 'Release~6 Patchlevel~5', 'N', '1997-08-01');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(39, 'Release~6 Patchlevel~6', 'N', '1997-10-23');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(40, 'Release~6 Patchlevel~7', 'N', '1997-12-11');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(41, 'Release~6 Patchlevel~8', 'N', '1998-04-03');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(42, 'Release~6 Patchlevel~9', 'N', '1998-04-16');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(43, 'Release~6 Patchlevel~10', 'N', '1998-04-29');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(44, 'Release~6 Patchlevel~11', 'N', '1998-07-23');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(45, 'Release~6 Patchlevel~12', 'N', '1999-01-08');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(46, 'Release~6 Patchlevel~13', 'N', '1999-07-10');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(47, 'Release~6 Patchlevel~14', 'N', '1999-07-22');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(48, 'Release~6 Patchlevel~15', 'Y', '2003-06-10');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(49, 'Release~6 Patchlevel~16', 'Y', '2003-09-28');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(50, 'Release~6 Patchlevel~17', 'Y', '2003-10-11');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(51, 'Version~6.2.0', 'Y', '2003-10-15');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(52, 'Version~6.2.1', 'Y', '2003-12-09');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(53, 'Version~6.4.0', 'Y', '2004-01-07');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(54, 'Version~6.5.2', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(55, 'Version~6.5.4', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(56, 'Version~6.5.8', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(57, 'Version~6.5.9', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(58, 'Version~6.5.16', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(59, 'Version~6.5.17', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(60, 'Version~6.5.19', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(61, 'Version~6.5.20', 'N', NULL);

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(62, 'Version~6.6.0', 'Y', '2004-06-16');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(63, 'Version~7.00', 'Y', '2010-03-01');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(64, 'Version~7.01', 'Y', '2010-05-24');

INSERT INTO VERS(VERS_ID, VERS, OFFICIAL_RELEASE, RELEASE_DATE) VALUES(65, 'Version~7.02', 'Y', '2013-05-02');
